_target_: src.models.mnist_module.MNISTLitModule

optimizer:
  _target_: torch.optim.SGD
  _partial_: true
  lr: 0.1
  weight_decay: 0.0001
  momentum: 0.9

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 5

net:
  _target_: src.models.components.ResNet.ResnetModel
  num_classes: 10
  channels: 1
  resnet_version: 152
